### ISSUE TITLE
EXE not working on my laptop

### ISSUE THREAD

**Issue by UWANNAPUNCAKE** [clienthax/SAOALTool#1]
Cant open exe on my laptop it just flashes the window border and disappears

**Comment by clienthax** [comment]
It's a command line tool

**Comment by UWANNAPUNCAKE** [comment]
> It's a command line tool

hey can you tell me the command line to use please and thank you

**Comment by UWANNAPUNCAKE** [comment]
Hello what’s the command to be able to activate the SAOtool hopefully using
CMD
